/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_CarteBancaire;

import static gestion_CarteBancaire.standard_mastercard.txt_civilité;
import static gestion_CarteBancaire.standard_mastercard.txt_dateexpiration;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Zakaria Nabil
 */
public class homme_cmi extends javax.swing.JFrame {

    /**
     * Creates new form homme_cmi
     */
    public homme_cmi() {
        initComponents();
         txt_nom.setText(Interface_Carte.txt_nom.getText());
        if(Interface_Carte.mr.isSelected())
        txt_civilité.setText("MR");
        else
            if(Interface_Carte.mlle.isSelected())
        txt_civilité.setText("MLLE");
        else
        if(Interface_Carte.mme.isSelected())
        txt_civilité.setText("MME");
        SimpleDateFormat df=new SimpleDateFormat("MM/yy");

        Interface_Carte.datecreation.getDate();
        Date date = Interface_Carte.datecreation.getDate();
        txt_dateexpiration.setDate((date));

        
      txt_numcompte.setText(Interface_Carte.txt_numcompte.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_numcompte = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_civilité = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_dateexpiration = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 4, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(338, 206));
        jPanel1.setMinimumSize(new java.awt.Dimension(338, 206));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ZAKARIA BANK");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 110, 34);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/icons8-puce-de-carte-sim-40.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 50, 49, 36);

        txt_numcompte.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_numcompte.setForeground(new java.awt.Color(255, 255, 0));
        txt_numcompte.setText("Numéro De Compte");
        jPanel1.add(txt_numcompte);
        txt_numcompte.setBounds(19, 100, 310, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VALID THRU");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 130, 58, 20);

        txt_nom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nom.setForeground(new java.awt.Color(255, 255, 0));
        txt_nom.setText("Nom Complet Du Client");
        jPanel1.add(txt_nom);
        txt_nom.setBounds(80, 160, 170, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/logos-paiement.png"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(256, 140, 70, 49);

        jLabel6.setFont(new java.awt.Font("Doppio One", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Credit Card");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 0, 150, 70);

        txt_civilité.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_civilité.setForeground(new java.awt.Color(255, 255, 0));
        txt_civilité.setText("Civ");
        jPanel1.add(txt_civilité);
        txt_civilité.setBounds(50, 160, 20, 20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/icons8-trier-à-gauche-38 (1).png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 150, 30, 40);

        txt_dateexpiration.setDateFormatString("MM/yy");
        txt_dateexpiration.setEnabled(false);
        jPanel1.add(txt_dateexpiration);
        txt_dateexpiration.setBounds(160, 130, 91, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/pngtree-men-s-luxury-watch-black-banner-image_182858.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(4, 2, 330, 190);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("R");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homme_cmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homme_cmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homme_cmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homme_cmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homme_cmi().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel txt_civilité;
    private static com.toedter.calendar.JDateChooser txt_dateexpiration;
    private javax.swing.JLabel txt_nom;
    private javax.swing.JLabel txt_numcompte;
    // End of variables declaration//GEN-END:variables
}
