
package gestion_CarteBancaire;

import gestionbancaires.client;
import gestionbancaires.gestionClient;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Interface_Carte extends javax.swing.JFrame {
    
    
static List <infos_carte>l=new ArrayList<infos_carte>();
    DefaultTableModel ml=new DefaultTableModel();
    String [] col={"Civilité","Nom Complet","Date D'Expiration ","Numéro De Compte","Type Carte","Style Carte"};
  int pos = -1;
    public Interface_Carte() {
        initComponents();
        ml.setColumnIdentifiers(col);
        this.jTable1.setModel(ml);
        CMI.setVisible(false);
        Visa.setVisible(false);
        MasterCard.setVisible(false);
         this.buttonGroup1.add(this.nationale);
        this.buttonGroup1.add(this.internationale);
         this.buttonGroup2.add(this.CMI);
        this.buttonGroup2.add(this.Visa);
        this.buttonGroup2.add(this.MasterCard);
        this.buttonGroup3.add(this.standard);
        this.buttonGroup3.add(this.homme);
        this.buttonGroup3.add(this.femme);
        this.buttonGroup6.add(this.mr);
        this.buttonGroup6.add(this.mlle);
        this.buttonGroup6.add(this.mme);
        //AUTO-IMPORT
        ///Import
                FileInputStream f=null;
              ObjectInputStream ff=null;
      
               try {
           
             f=new FileInputStream ("Liste Cartes Bancaires.txt");
        } catch (FileNotFoundException ex) {
        }
       try {
          ff=new ObjectInputStream(f);
        } catch (IOException ex) {
        }
        try {
       l=(List<infos_carte>)ff.readObject();
          SimpleDateFormat df=new SimpleDateFormat("MM/yy");
       for(infos_carte e:l)
       {
          ml.addRow(new Object[]{e.getCivilité(),e.getNom(),df.format(e.getDateexpiration()),e.getNumcompte(),e.getType(),e.getStyle()});
       
        }} catch (IOException ex) {
        } catch (ClassNotFoundException ex) {
        }
        try {
            ff.close();
        } catch (IOException ex) {
            Logger.getLogger(gestionClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        //
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        mr = new javax.swing.JRadioButton();
        mlle = new javax.swing.JRadioButton();
        mme = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        nationale = new javax.swing.JRadioButton();
        internationale = new javax.swing.JRadioButton();
        CMI = new javax.swing.JRadioButton();
        Visa = new javax.swing.JRadioButton();
        MasterCard = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        standard = new javax.swing.JRadioButton();
        homme = new javax.swing.JRadioButton();
        femme = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txt_numcompte = new javax.swing.JFormattedTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        datecreation = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 845, 571));
        setMaximumSize(new java.awt.Dimension(1176, 599));
        setMinimumSize(new java.awt.Dimension(1176, 599));
        setPreferredSize(new java.awt.Dimension(1368, 635));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/icons8-ajouter-une-propriété-26.png"))); // NOI18N
        jButton2.setText(" Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 10, 180, 30);

        jButton4.setBackground(new java.awt.Color(0, 102, 204));
        jButton4.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/icons8-supprimer-la-propriété-26.png"))); // NOI18N
        jButton4.setText(" Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(350, 10, 200, 30);

        jButton8.setBackground(new java.awt.Color(0, 102, 204));
        jButton8.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/icons8-modifier-la-propriété-26.png"))); // NOI18N
        jButton8.setText(" Modifier");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(630, 10, 180, 30);

        jButton9.setBackground(new java.awt.Color(0, 102, 204));
        jButton9.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/icons8-machine-virtuelle-26.png"))); // NOI18N
        jButton9.setText("  Trier");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(890, 10, 190, 30);

        jButton10.setBackground(new java.awt.Color(255, 0, 0));
        jButton10.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jButton10.setText("Quitter");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(1130, 10, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 550, 1360, 50);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion De La Carte Bancaire");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel2.setText("Nom Du Client  : ");

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel3.setText("Civilité  :");

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel4.setText("Date D'Éxpiration  : ");

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel5.setText("Type :");

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel6.setText("Style :");

        txt_nom.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        txt_nom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        mr.setBackground(new java.awt.Color(255, 255, 255));
        mr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mr.setText("Mr");

        mlle.setBackground(new java.awt.Color(255, 255, 255));
        mlle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mlle.setText("Mlle");

        mme.setBackground(new java.awt.Color(255, 255, 255));
        mme.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mme.setText("Mme");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(mr)
                .addGap(18, 18, 18)
                .addComponent(mlle)
                .addGap(18, 18, 18)
                .addComponent(mme, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mlle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        nationale.setBackground(new java.awt.Color(255, 255, 255));
        nationale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nationale.setText("Nationale");
        nationale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationaleActionPerformed(evt);
            }
        });

        internationale.setBackground(new java.awt.Color(255, 255, 255));
        internationale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        internationale.setText("Internationale");
        internationale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internationaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nationale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(internationale, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nationale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(internationale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CMI.setBackground(new java.awt.Color(255, 255, 255));
        CMI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CMI.setText("CMI");
        CMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMIActionPerformed(evt);
            }
        });

        Visa.setBackground(new java.awt.Color(255, 255, 255));
        Visa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Visa.setText("Visa");
        Visa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisaActionPerformed(evt);
            }
        });

        MasterCard.setBackground(new java.awt.Color(255, 255, 255));
        MasterCard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MasterCard.setText("MasterCard");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        standard.setBackground(new java.awt.Color(255, 255, 255));
        standard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        standard.setText("Standard");

        homme.setBackground(new java.awt.Color(255, 255, 255));
        homme.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        homme.setText("Homme");

        femme.setBackground(new java.awt.Color(255, 255, 255));
        femme.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        femme.setText("Femme");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(standard)
                .addGap(47, 47, 47)
                .addComponent(homme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(femme)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standard)
                    .addComponent(homme)
                    .addComponent(femme))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/pngtree-men-s-luxury-watch-black-banner-image_182858.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/CoxFNk.jpg"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Aperçu");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel7.setText("Numéro De Compte :");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/icons8-souvenirs-32.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        try {
            txt_numcompte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####    ####    ####    ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/icons8-reset-24.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Civilité", "Nom Complet ", "Date D'expiration", "Numéro De Compte", "Type Carte", "Style"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionbancaires/icons8-accueil-30.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_CarteBancaire/icons8-chercher-16.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(CMI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Visa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MasterCard)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jButton6))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(datecreation, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txt_numcompte, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(txt_nom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(datecreation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(txt_numcompte)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Visa)
                            .addComponent(MasterCard)
                            .addComponent(CMI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(11, 11, 11)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1370, 550);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(800, 250, 84, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMIActionPerformed

    private void nationaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationaleActionPerformed
        CMI.setVisible(true);
         MasterCard.setVisible(false);
       Visa.setVisible(false);
    }//GEN-LAST:event_nationaleActionPerformed

    private void internationaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internationaleActionPerformed
       CMI.setVisible(false);
        MasterCard.setVisible(true);
       Visa.setVisible(true);
    }//GEN-LAST:event_internationaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ///CMI
        if(this.CMI.isSelected()&&this.standard.isSelected())
        {
            standard_cmi sc = new standard_cmi();
            sc.setVisible(true);
            
        }
        else
            if(this.CMI.isSelected()&&this.homme.isSelected())
            {
               homme_cmi hc = new homme_cmi();
               hc.setVisible(true); 
            }
        else
            if(this.CMI.isSelected()&&this.femme.isSelected())
            {
               femme_cmi fc = new femme_cmi();
               fc.setVisible(true); 
            }
        ///MasterCard
        if(this.MasterCard.isSelected()&&this.standard.isSelected())
        {
            standard_mastercard sm = new standard_mastercard();
            sm.setVisible(true);
            
        }
        else
            if(this.MasterCard.isSelected()&&this.homme.isSelected())
            {
               homme_mastercard hm = new homme_mastercard();
               hm.setVisible(true); 
            }
        else
            if(this.MasterCard.isSelected()&&this.femme.isSelected())
            {
               femme_mastercard fm = new femme_mastercard();
               fm.setVisible(true); 
            }
        /// VISA
        if(this.Visa.isSelected()&&this.standard.isSelected())
        {
            standard_visa sv = new standard_visa();
            sv.setVisible(true);
            
        }
        else
            if(this.Visa.isSelected()&&this.homme.isSelected())
            {
               homme_visa hv = new homme_visa();
               hv.setVisible(true); 
            }
        else
            if(this.Visa.isSelected()&&this.femme.isSelected())
            {
               femme_visa fv = new femme_visa();
               fv.setVisible(true); 
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
/*Random x = new Random();
        String a =Double.toString( x.nextInt(1515155445));
        String b =Integer.toString( x.nextInt(9999));
        String c =Integer.toString( x.nextInt(9999));
        String d =Integer.toString( x.nextInt(9999));
/*txt_numcomp1.setText(a);
txt_numcomp2.setText(b);
txt_numcomp3.setText(c);
txt_numcomp4.setText(d);*/

long first14 = (long) (Math.random() * 10000000000000000L);
String strLong = Long.toString(first14);
txt_numcompte.setText(strLong);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       txt_nom.setText(null);
       mr.setSelected(true);
       datecreation.setDate(null);
       txt_numcompte.setText(null);
       nationale.setSelected(true);
       CMI.setVisible(false);
       Visa.setVisible(false);
       MasterCard.setVisible(false);
      standard.setSelected(true);
      homme.setSelected(false);
      femme.setSelected(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String numcompte = this.txt_numcompte.getText();
             
    boolean b=true;    
    
     
          for(infos_carte p:l)
        {
            if(p.getNumcompte().equalsIgnoreCase(numcompte))
            {   
                b=false;
              
                JOptionPane.showMessageDialog(this, "La Carte Portant Le Numéro De Compte "+numcompte+" Est Déjà Ajouté", "Remarque", 
                               JOptionPane.ERROR_MESSAGE);
                
            }
          
            
            
        }
          
            String nom = this.txt_nom.getText();
       
        String civilité=null;
        if(this.mr.isSelected())
        civilité="Monsieur";
        else
            if(this.mlle.isSelected())
        civilité="Mademoiselle";
        else
            if(this.mme.isSelected())
        civilité="Madame";
         SimpleDateFormat df=new SimpleDateFormat("MM/yy");
         Date datecreation = this.datecreation.getDate();
         String type=null;
        if(this.nationale.isSelected()&&this.CMI.isSelected())
        type="C.M.I";
        else
            if(this.internationale.isSelected()&&this.Visa.isSelected())
        type="Visa";
        else
            if(this.internationale.isSelected()&&this.MasterCard.isSelected())
        type="MasterCard";
         String style=null;
        if(this.standard.isSelected())
        style="Standard";
        else
            if(this.homme.isSelected())
        style="Homme";
        else
            if(this.femme.isSelected())
        style="Femme";

        if(this.txt_nom.getText().equals("")||this.txt_numcompte.getText().equals("")||this.datecreation.getDate()==null)

        { JOptionPane.showMessageDialog(this,"Veuillez Remplir Tous Les Champs","Erreur Lors De La Saisie",JOptionPane.ERROR_MESSAGE);b=false;}

       
      
        
   
  infos_carte e =null;
     
        if(b)
         {
             e=new  infos_carte(civilité,nom,datecreation,numcompte,type,style);
            l.add(e);
            ml.addRow(new Object[]{e.getCivilité(),e.getNom(),df.format(e.getDateexpiration()),e.getNumcompte(),e.getType(),e.getStyle()});
       
         }
      //// Save
          FileOutputStream f=null;
        ObjectOutputStream ff=null;
    
        

        try
        {
            f=new FileOutputStream ("Liste Cartes Bancaires.txt");
            ff= new ObjectOutputStream(f);
            ff.writeObject(l);
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        finally
        {
            try {
                 
                ff.close();
               
           }catch (IOException ex) {
            }
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Menu m = new Menu();
       m.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void VisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int ligneselectionne=this.jTable1.getSelectedRow();
        int rep=JOptionPane.showConfirmDialog(this, "Étes Vous Sur De Vouloir Supprimer La Carte Portant Le Numéro De Compte  "+txt_numcompte.getText()+" ?","Suppression",JOptionPane.YES_NO_OPTION);
        if(rep==JOptionPane.YES_OPTION) 
        {ml.removeRow(ligneselectionne);
            l.remove(ligneselectionne);} 
        //// Save
          FileOutputStream f=null;
        ObjectOutputStream ff=null;
    
        

        try
        {
            f=new FileOutputStream ("Liste Cartes Bancaires.txt");
            ff= new ObjectOutputStream(f);
            ff.writeObject(l);
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        finally
        {
            try {
                 
                ff.close();
                 
           }catch (IOException ex) {
            }
        
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed
public int Rechercher()
    {  String numcompte = this.txt_numcompte.getText();
        int pos = -1;
        for(int i=0;i<l.size();i++)
        {
            if(l.get(i).getNumcompte().equalsIgnoreCase(numcompte))
                pos = i ;  
        }
          return pos ; 
    }  
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
String numcompte = this.txt_numcompte.getText();
             
    boolean b=true;    
    
     
          for(infos_carte p:l)
        {
            if(p.getNumcompte().equalsIgnoreCase(numcompte))
            {   
                b=false;
              
                JOptionPane.showMessageDialog(this, "La Carte Portant Le Numéro De Compte "+numcompte+" Est Déjà Ajouté", "Remarque", 
                               JOptionPane.ERROR_MESSAGE);
                
            }
         }
          
            String nom = this.txt_nom.getText();
       
        String civilité=null;
        if(this.mr.isSelected())
        civilité="Monsieur";
        else
            if(this.mlle.isSelected())
        civilité="Mademoiselle";
        else
            if(this.mme.isSelected())
        civilité="Madame";
         SimpleDateFormat df=new SimpleDateFormat("MM/yy");
         Date datecreation = this.datecreation.getDate();
         String type=null;
        if(this.nationale.isSelected()&&this.CMI.isSelected())
        type="C.M.I";
        else
            if(this.internationale.isSelected()&&this.Visa.isSelected())
        type="Visa";
        else
            if(this.internationale.isSelected()&&this.MasterCard.isSelected())
        type="MasterCard";
         String style=null;
        if(this.standard.isSelected())
        style="Standard";
        else
            if(this.homme.isSelected())
        style="Homme";
        else
            if(this.femme.isSelected())
        style="Femme";

        if(this.txt_nom.getText().equals("")||this.txt_numcompte.getText().equals("")||this.datecreation.getDate()==null)

        { JOptionPane.showMessageDialog(this,"Veuillez Remplir Tous Les Champs","Erreur Lors De La Saisie",JOptionPane.ERROR_MESSAGE);b=false;}

       if(b==true)
     
  if (pos != -1)
{
  this.jTable1.removeRowSelectionInterval(pos, pos);
  pos = Rechercher();
}
if(pos ==-1)
{
    JOptionPane.showMessageDialog(this," La Carte  Portant Le Numéro De Compte \t"+txt_numcompte.getText()+"\t Est Introuvable ","Échec De La Modification",JOptionPane.ERROR_MESSAGE);
}
else
    //(civilité,nom,datecreation,numcompte,type,style);
        {
            l.get(pos).setCivilité(civilité);
            l.get(pos).setNom(nom);
            l.get(pos).setDateexpiration(datecreation);
            l.get(pos).setNumcompte(numcompte);
            l.get(pos).setType(type);
            l.get(pos).setStyle(style);
            
            
          
          ml.setValueAt(nom, pos, 1);
          ml.setValueAt(df.format(datecreation), pos, 2);
          ml.setValueAt(numcompte, pos, 3);
          ml.setValueAt(type, pos, 4);
          ml.setValueAt(style, pos,5 );

          
          
                                        
            
        }
  //// Save
          FileOutputStream f=null;
        ObjectOutputStream ff=null;
    
        

        try
        {
            f=new FileOutputStream ("Liste Cartes Bancaires.txt");
            ff= new ObjectOutputStream(f);
            ff.writeObject(l);
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        finally
        {
            try {
                 
                ff.close();
                JOptionPane.showMessageDialog(this, "Modification Enregistrée Dans Le Fichier ","Sauvegarde réussie", JOptionPane.INFORMATION_MESSAGE);
                 
           }catch (IOException ex) {
            }
        
        }
      
        
          
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(pos!=-1)
        this.jTable1.removeRowSelectionInterval(pos, pos);

    pos=Rechercher();
   if(pos==-1)
   {
       JOptionPane.showMessageDialog(this,"Carte Avec Ce Numéro De Compte Introuvable","Echec Recherche",JOptionPane.ERROR_MESSAGE);
   }
   else
   {
        //(civilité,nom,datecreation,numcompte,type,style);
       ///CIVILITÉ
       if(l.get(pos).getCivilité().equalsIgnoreCase("Mr"))
           this.mr.setSelected(true);
       else
         if(l.get(pos).getCivilité().equalsIgnoreCase("Mlle"))
           this.mlle.setSelected(true);
       else   
        if(l.get(pos).getCivilité().equalsIgnoreCase("Mme"))
           this.mme.setSelected(true);
       //Nom ,DateExpiration , Num Compte
       this.txt_nom.setText(String.valueOf(l.get(pos).getNom()));
       this.datecreation.setDate(l.get(pos).getDateexpiration());
       this.txt_numcompte.setText(l.get(pos).getNumcompte());
       ///TYPE CARTE
       if(l.get(pos).getType().equalsIgnoreCase("CMI"))
       {  
          nationale.setSelected(true);
          CMI.setVisible(true);
          this.CMI.setSelected(true);
       }
       else
         if(l.get(pos).getType().equalsIgnoreCase("Visa"))
         {   this.internationale.setSelected(true);
             this.Visa.setVisible(true);
             this.Visa.setSelected(true);
         }
       else   
        if(l.get(pos).getType().equalsIgnoreCase("MasterCard"))
        {   this.internationale.setSelected(true);
            this.MasterCard.setVisible(true);
            this.MasterCard.setSelected(true);
        }
       /// STYLE CARTE
       if(l.get(pos).getStyle().equalsIgnoreCase("Standard"))
           this.standard.setSelected(true);
       else
         if(l.get(pos).getStyle().equalsIgnoreCase("Homme"))
           this.homme.setSelected(true);
       else   
        if(l.get(pos).getStyle().equalsIgnoreCase("Femme"))
           this.femme.setSelected(true);
       
       
        this.jTable1.addRowSelectionInterval(pos, pos);
      
   }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Collections.sort(l);
      Collections.reverse(l);

      ml.setRowCount(0);
         SimpleDateFormat df=new SimpleDateFormat("MM/yy");
          
      for(infos_carte e:l)
      {
          ml.addRow(new Object[]{e.getCivilité(),e.getNom(),df.format(e.getDateexpiration()),e.getNumcompte(),e.getType(),e.getStyle()});
       }       
        //// Save
          FileOutputStream f=null;
        ObjectOutputStream ff=null;
    
        

        try
        {
            f=new FileOutputStream ("Liste Cartes Bancaires.txt");
            ff= new ObjectOutputStream(f);
            ff.writeObject(l);
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        finally
        {
            try {
                 
                ff.close();
                
           }catch (IOException ex) {
            }
        
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Carte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Carte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Carte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Carte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Carte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CMI;
    private javax.swing.JRadioButton MasterCard;
    private javax.swing.JRadioButton Visa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private com.toedter.calendar.JDateChooser datecreation;
    private javax.swing.JRadioButton femme;
    private javax.swing.JRadioButton homme;
    private javax.swing.JRadioButton internationale;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JRadioButton mlle;
    public static javax.swing.JRadioButton mme;
    public static javax.swing.JRadioButton mr;
    private javax.swing.JRadioButton nationale;
    private javax.swing.JRadioButton standard;
    public static javax.swing.JTextField txt_nom;
    public static javax.swing.JFormattedTextField txt_numcompte;
    // End of variables declaration//GEN-END:variables
}
