/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_Transaction;

import static gestion_CarteBancaire.Interface_Carte.txt_numcompte;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Zakaria Nabil
 */
public class recu extends javax.swing.JFrame {

    /**
     * Creates new form recu
     */
    public recu() {
        initComponents();
         SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");        
        Date date=Interface_Transaction.datetransaction.getDate();
        txt_nomemeteur.setText(Interface_Transaction.txt_emetteur.getText());
      txt_numcompte.setText(Interface_Transaction.txt_numcompte.getText());
      txt_nomrecepteur.setText(Interface_Transaction.txt_nom2.getText());
      txt_numcompte2.setText(Interface_Transaction.txt_numcompte2.getText());
      txt_montant.setText(Interface_Transaction.txt_montant.getText()+"Dhs");
      datetransaction.setText(df.format(date));
      
       long first14 = (long) (Math.random() * 10000L);
String strLong = Long.toString(first14);
txt_numvers.setText(strLong); 
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nomemeteur = new javax.swing.JLabel();
        txt_numcompte = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nomrecepteur = new javax.swing.JLabel();
        txt_numcompte2 = new javax.swing.JLabel();
        txt_montant = new javax.swing.JLabel();
        datetransaction = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_numvers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(743, 380));
        setMinimumSize(new java.awt.Dimension(743, 380));
        setPreferredSize(new java.awt.Dimension(743, 380));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ZAKARIA BANK");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(550, 0, 190, 60);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setText("Envoyé Par : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 90, 140, 40);

        txt_nomemeteur.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jPanel1.add(txt_nomemeteur);
        txt_nomemeteur.setBounds(160, 90, 170, 50);

        txt_numcompte.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        txt_numcompte.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txt_numcompte);
        txt_numcompte.setBounds(330, 90, 240, 50);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("A   :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 160, 150, 30);

        txt_nomrecepteur.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        txt_nomrecepteur.setPreferredSize(new java.awt.Dimension(41, 27));
        jPanel1.add(txt_nomrecepteur);
        txt_nomrecepteur.setBounds(160, 160, 150, 40);

        txt_numcompte2.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        txt_numcompte2.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(txt_numcompte2);
        txt_numcompte2.setBounds(330, 160, 240, 40);

        txt_montant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_montant.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txt_montant);
        txt_montant.setBounds(590, 270, 140, 30);

        datetransaction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(datetransaction);
        datetransaction.setBounds(590, 300, 140, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("GUICHETIER :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CLIENT :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 220, 340, 130);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("BORDEREAU DE Versement En Espèce No");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(143, 45, 340, 30);

        txt_numvers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txt_numvers);
        txt_numvers.setBounds(480, 44, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel datetransaction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel txt_montant;
    public static javax.swing.JLabel txt_nomemeteur;
    public static javax.swing.JLabel txt_nomrecepteur;
    private javax.swing.JLabel txt_numcompte;
    public static javax.swing.JLabel txt_numcompte2;
    private javax.swing.JLabel txt_numvers;
    // End of variables declaration//GEN-END:variables
}
